<?php
 // module/Album/view/album/album/delete.phtml:

 $title = 'Delete categorie';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Are you sure that you want to delete
     '<?php echo $this->escapeHtml($categorie->titre); ?>' by
     '<?php echo $this->escapeHtml($categorie->image); ?>'?
 </p>
 <?php
 $url = $this->url('categorie', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $categorie->id; ?>" />
     <input type="submit" name="del" value="Oui" />
     <input type="submit" name="del" value="Non" />
 </div>
 </form>