<?php
$title = 'Add new film';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('film', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('categorie'));
 echo $this->formRow($form->get('question'));
 echo $this->formRow($form->get('prop1'));
 echo $this->formRow($form->get('prop2'));
 echo $this->formRow($form->get('prop3'));
 echo $this->formRow($form->get('prop4'));
 echo $this->formRow($form->get('reponse'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();