<?php
$title = 'Choisissez un thème';
 $this->headTitle($title);
 ?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<p><a href="<?php echo $this->url('histoire',
             array('action'=>'index'));?>">histoire de france</a></p>
<p><a href="<?php echo $this->url('histoire',
             array('action'=>'index'));?>">Le rois Soleil</a></p>
<p><a href="<?php echo $this->url('histoire',
             array('action'=>'index'));?>">L'instrialisation</a></p>
